### ISSUE TITLE
ncmpcpp and not the terminal name.

### ISSUE THREAD

**Issue by KoO-303** [cboddy/i3-workspace-names-daemon#24]
Would it be possible to use the programs names that run in a terminal instead of the terminal name.
In the example below the workspace name is always shown as urxvt and not ncmpcpp this is the same for every program that is run from a terminal. ranger , calcurse.  etc.. 
bindsym $mod+n exec --no-startup-id urxvt -e ncmpcpp
assign [title="ncmpcpp"] workspace number $ws2

Thanks

**Comment by luukvbaal** [comment]
The script looks for the `WM_CLASS` string as shown by `xprop`. Suckless' simple terminal allows you to assign a custom class when launching a terminal which would allow you to launch a terminal application like so:
`$mod+n exec --no-startup-id st -c ncmpcpp -e ncmpcpp`.

I'm sure there are other terminals that can do this but I believe `urxvt` only allows you to set `WM_INSTANCE` through the `-name` tag like so:
`urxct -name ncmcpp -e ncmpcpp`

You would have to modify the script to look for the instance name instead of the class. I did something similar in #23.

**Comment by KoO-303** [comment]
Thanks very much for your reply.
st indeed will use custom class name with the -c name and now only use st to run my cli programs.
$mod+n exec --no-startup-id st -c ncmpcpp -e ncmpcpp

I have tried urxvt -name and -n with no luck. 
May look into urxvt at a later date will inform if I find anything, but for now i'm Happy with st.
